language: java
install: ant

notifications:
  email:
    recipients:
      - miguetoscano288@gmail.com
      - constanza.viere@gmail.com
    on_success: always # default: change

    on_failure: always # defaults: always

jdk:
  - openjdk8
